### ISSUE TITLE
Replace function not flexible enough

### ISSUE THREAD

**Issue by mysth** [beberlei/DoctrineExtensions#146]
Here, what i need to do : 

    REPLACE(s.rank, s.rank , s.rank + 1)

with the actual code i got :

    Error : Expected Doctrine\Orm\Query\Lexer::T_CLOSE_PARENTHESIS, got '+'

**Comment by smilesrg** [comment]
Maybe this one is useful? https://gist.github.com/K-Phoen/6108436

**Comment by shibby** [comment]
This issue can be closed because dql that you wrote is wrong. 
you have to use as `(s.rank +1)`

**Comment by mysth** [comment]
Why do we need these brackets ? There is nothing else in the third parameter ... ?

**Comment by shibby** [comment]
Because it uses Arithmetic parser and it expects brackets.

Also you can't use something like that. Actually you can, but it will not increase.
`UPDATE FROM Entity e SET e.rank = e.rank+1`
You need to use
`(e.rank+1)`

So, functions need to all same i guess. We can't change update expression, but we can use other functions like update expression.
