### ISSUE TITLE
ZF2 support docs

### ISSUE THREAD

**Issue by jarrettj** [beberlei/DoctrineExtensions#248]
Hi,

Good day.

Any docs on how to get this to work on ZF2 using doctrine2? 

I get the following error:
`Fatal error: Uncaught Error: Class 'DoctrineExtensions\Query\MySql\StrToDate' not found in /mnt/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:3497 
`

I've added the following to my module.config.php:
```
'string_functions' => array(
                    'STR_TO_DATE' => 'DoctrineExtensions\Query\MySql\StrToDate',
                    'YEAR' => 'DoctrineExtensions\Query\MySql\Year',
                )
```

Weird is that it only happens in production, and not on my local machine. Thanks.

Regards.
JJ

**Comment by stevelacey** [comment]
@jarrettj you're mis-referencing the class, the`MySql` namespace is actually cased as `MySQL.

The reason you're seeing it in production-only is probably because you're (correctly) using the Composer optimised autoloader in production, where it uses a classmap for loading dependencies, rather than on-the-fly handling you'd use in dev – IIRC the optimised autoloader is case-sensitive whilst the default for dev is not – because PHP is generally not case sensitive – but the classmap is literally a key value map of class names to file paths which needs exact matches.

**Comment by jarrettj** [comment]
@stevelacey Awesome!

Thanks for the reply. Damn that optimised autoloader! :)

**Comment by stevelacey** [comment]
@jarrettj no problem, I am always happy when my obscure knowledge of things that no one should need to know helps someone out
